# Metadata about this component, to be used in the CMS
spec:
  array_structures:
    - content_blocks
  label: Spacer section
  description: This section is used to add the specified space
  icon: expand
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  space: 30px

# Overrides any fields in the blueprint when viewing this component in the component browser
preview: {}

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  space:
    comment: Default value for the spacer section ex-30px
