source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.2.1"
  gem 'jekyll-watch'
  gem 'jekyll-sass-converter', :git => "https://github.com/CloudCannon/jekyll-sass-converter.git"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-local-assign'
  gem 'jekyll-pagebreak', '~> 0.6.0'
end
