source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", ">= 2.2.0"
  gem "cloudcannon-jekyll-bookshop", ">= 2.2.0"
  gem 'jekyll-watch'
  gem 'jekyll-postcss-v2'
  gem 'jekyll-local-assign'
  gem 'jekyll-pagebreak', '~> 0.8.0'
end
